### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by Hashim1999164** [chris1111/Notarized-RT2870USBWirelessDriver#1]
Does it works with Big sur 11.3.1 ? and Moneterey? Will it work on Hackintosh? (Opencore)

**Comment by chris1111** [comment]
Yes working Big Sur 11 and Monterey 12. Working with Hackintosh of course!
Read [the guide ](https://github.com/chris1111/Notarized-RT2870USBWirelessDriver/blob/Master/Guide.pdf)
