### ISSUE TITLE
No Connection!!

### ISSUE THREAD

**Issue by vkocev** [chris1111/Notarized-RT2870USBWirelessDriver#2]
I can confirm that it dosen't work on Monterey 12.1 (21C52). I have 2 usb dongles which work on High Sierra. I tried everything, SIP disable/enable. It loads the kext, I can see the adapters in System Prefrences>Network. But the app says No Connection. I am sure I am editing the plist just fine. I edited the ActiveProfile.plist and Advnaced manually but still no luck. Please explain which MAC address should I put in BSSD? Is this the Acess Point MAC address (of the WIFI router) or the Ethernet en0 or the wifi dongle MAC address. My ethernet is en0. The wifi dongles are shown as en2 and en3 in System Information>Network. Please also explain what are the preferences for WPA2 and also for OPEN netwrok without password. In terms of Encryption Type, Authenticaion type, Network Mode (mode 9), etc (PSK+TKIP, etc). I see mode 13 in High Siera mediatek app. It is easier to connect without password and test from there. Maybe the error is somewhere in these parameters. Please note that the driver I use in High Sierra is version 5.0.1.2.2 and it is larger kext file, some 4MB and yours (5.0.1.35) kext is 1.5 MB. Can I use the driver from High Sierra? `Thanks

Your extension
![Screenshot 2022-01-24 at 12 47 02](https://user-images.githubusercontent.com/98319475/150778255-857c9b7d-c950-47fd-a84b-15dc33d12b90.png)

![Screenshot 2022-01-24 at 12 46 41](https://user-images.githubusercontent.com/98319475/150778409-b2101cf1-e4d1-42ec-a675-47cfa2eab59e.png)

![Screenshot 2022-01-24 at 12 46 25](https://user-images.githubusercontent.com/98319475/150778525-337d804a-32ae-4d50-8264-ef5a098b30c1.png)

![Screenshot 2022-01-24 at 12 46 09](https://user-images.githubusercontent.com/98319475/150778536-008356f0-1cc1-4179-8af3-ca69876db1cb.png)

![Screenshot 2022-01-24 at 12 45 49](https://user-images.githubusercontent.com/98319475/150778549-4e176bdd-c699-4e30-a0c2-31ce586cf892.png)

![Screenshot 2022-01-24 at 12 45 36](https://user-images.githubusercontent.com/98319475/150778569-07a63402-c9f9-4806-abc7-047bf7b876b6.png)

**Comment by chris1111** [comment]
Tou confirm Nothing  because I have already confirm working

**Comment by vkocev** [comment]
@chris1111 Well can you help?  Sorry for the confirm, but I cannot make it work?

**Comment by chris1111** [comment]
Help of what You have all the information here
